### ISSUE TITLE
label option doesn't work with Matplotlib 

### ISSUE THREAD

**Issue by yaboojp** [red-data-tools/charty#10]
Execute following, not displayed label.

```ruby
charty = Charty.new(:matplot)

bar = charty.bar do
  series [0,1,2,3,4], [10,40,20,90,70], label: "sample1"
  series [0,1,2,3,4], [90,80,70,60,50], label: "sample2"
  series [0,1,2,3,4,5,6,7,8], [50,60,20,30,10, 90, 0, 100, 50], label: "sample3"
  range x: 0..10, y: 1..100
  xlabel 'foo'
  ylabel 'bar'
  title 'bar plot'
end
bar.render("bar_matplot.png")
```

/w Matplotlib
![image](https://user-images.githubusercontent.com/387427/56466625-ef81d200-644e-11e9-88b9-21ce1345290a.png)

/w Gruff
![image](https://user-images.githubusercontent.com/387427/56466622-ea248780-644e-11e9-8e75-9866321286c1.png)

**Comment by mrkn** [comment]
@yaboojp Do you mean a legend isn't displayed with matplotlib backend?

**Comment by 284km** [comment]
Now the label is displayed.

```ruby
charty = Charty.new(:matplot)

bar = charty.bar do
  series [0,1,2,3,4], [10,40,20,90,70], label: "sample1"
  series [0,1,2,3,4], [90,80,70,60,50], label: "sample2"
  series [0,1,2,3,4,5,6,7,8], [50,60,20,30,10, 90, 0, 100, 50], label: "sample3"
  range x: 0..10, y: 1..100
  xlabel 'foo'
  ylabel 'bar'
  title 'bar plot'
end
bar.render("bar_matplot.png")
```

![bar_matplot](https://user-images.githubusercontent.com/1458041/58471552-1aaebe00-817f-11e9-81b3-715f15dd258a.png)
