### ISSUE TITLE
Rake tasks to update xkcd and css3 named colors

### ISSUE THREAD

**Issue by mrkn** [red-data-tools/charty#41]
In #36, xkcd and css3 named colors will be introduced.
It would be much better if there are rake tasks updating them.

See https://github.com/red-data-tools/charty/pull/36#discussion_r333837802 and https://github.com/red-data-tools/charty/pull/36#discussion_r333837879.

**Comment by kou** [comment]
Moved to https://github.com/red-data-tools/red-colors/issues/8 .
