### ISSUE TITLE
Add Google Charts backend support

### ISSUE THREAD

**Issue by indigolain** [red-data-tools/charty#7]
I would like to add Google Charts support as the backend rendering engine in Charty.

I have coded a small example for the idea of the implementation, so it would be great if I could get some feedback on if I'm going in the right direction and also, some hints on what I would need to implement further.

This is my branch with  the implementation: https://github.com/indigolain/charty/tree/add_google_charts_backend

**Comment by kou** [comment]
Could you create a pull request for the branch?
Then we can discuss this with code.

**Comment by indigolain** [comment]
Thank you for the response!
I have created a pull request [here](https://github.com/red-data-tools/charty/pull/11)

**Comment by kou** [comment]
Thanks!
