### ISSUE TITLE
The README codes does not work in rubydata/minimal-notebook:latest Docker container.

### ISSUE THREAD

**Issue by kozo2** [red-data-tools/charty#97]
The screenshot is 
![image](https://user-images.githubusercontent.com/12192/212852251-d4bbcfed-7d7c-4e01-a9e4-1af704dae9df.png)

To reproduce this,
1. Create a Docke container with https://github.com/kozo2/quarto4rubydata#%E4%B8%8A%E8%A8%98%E3%81%AE%E8%A9%A6%E7%94%A8%E3%82%92-docker-%E3%82%92%E7%94%A8%E3%81%84%E3%81%A6%E3%81%94%E8%87%AA%E8%BA%AB%E3%81%AE%E3%83%AD%E3%83%BC%E3%82%AB%E3%83%AB%E7%92%B0%E5%A2%83%E3%81%A7%E8%A1%8C%E3%81%86%E3%81%AB%E3%81%AF
2. Open `localhost:8888`.
3. Open and Run `try_charty.ipynb'

**Comment by mrkn** [comment]
This shouldn't be due to charty, but It should be RubyData/docker-stacks's issue.  The instruction described in the following page should be done in the Dockerfile of the images of RubyData/docker-stacks.

https://plotly.com/python/getting-started/#jupyterlab-support

**Comment by kozo2** [comment]
Thank you for your reply.
However, I later found that this issue is difficult to understand which error improvement I want.
I close this issue and resubmit an issue with a clear target for advice.
I know how to update RubyData/docker-stacks and I will do that.
